---
   - name: creating directory with the name of client
     file:
        path: /root/openvpn_docker/{{ ansible_ssh_host }}
        recurse: yes
        state: directory
   
   - name: copying files to {{ client_name }} directory
     copy:
        src: "{{ client_files_path }}"
        dest: /root/openvpn_docker/{{ ansible_ssh_host }}/
        mode: 0755 
   
   - name: pulling docker image
     docker_image:
        name: akashsandy/openvpn
        tag: latest
        source: pull

   - name: checking available ports     
     block:
        - name: assigning ports
          script: port_check     
          register: sshport  
          when: ssh_port == ""

   - set_fact:
       ssh_port: "{{ sshport.stdout }}"
     when: ssh_port == ""

   - name: debug port
     debug:
       msg: "{{ ssh_port }}"

   - name: start openvpn container
     docker_container:
        name: "{{ ansible_ssh_host }}"
        image: akashsandy/openvpn
        state: started
        ports:
           - "{{ ssh_port }}:22"
        devices:
           - "/dev/net/tun"
        env:
           OVPN_FILE: "{{ovpn_file}}"
           PKCS12_FILE: "{{pkcs12_file}}"
           PASS_FILE: "{{pass_file}}"
           OVPN_USERNAME: "{{username}}"
           OVPN_PASSWORD: "{{password}}"
        capabilities:
           - NET_ADMIN
        sysctls: net.ipv6.conf.all.disable_ipv6=0
        volumes:
           - /root/openvpn_docker/{{ ansible_ssh_host }}/:/client/
        detach: true

   - name: register container status
     shell: "sleep 2;docker logs {{ ansible_ssh_host }} | grep -E 'openvpn|sshd'"
     register: status

   - name: debug container status
     debug:
        msg: "{{ status.stdout_lines }}"

   - name: register openvpn status
     shell: "sleep 3;docker exec -it {{ ansible_ssh_host }} tail -5 /var/log/openvpn/vpn_out.log" 
     register: openvpn

   - name: debug openvpn status
     debug:
        msg: "{{ openvpn.stdout_lines }}"
...
