---
- name: creating directory with the name of client
  file:
     path: /root/openvpn_docker/{{ ansible_ssh_host }}
     recurse: yes
     state: directory
   
- name: copying files to remote machine
  copy:
     src: "{{ client_files_path }}"
     dest: /root/openvpn_docker/{{ ansible_ssh_host }}/
     mode: 0755 
   
- name: pulling docker image
  docker_image:
     name: akashsandy/openvpn
     tag: latest
     source: pull
...
