---
- name: start openvpn container
  docker_container:
     name: "{{ ansible_ssh_host }}"
     image: akashsandy/openvpn
     state: started
     ports:
        - "{{ ssh_port }}:22"
     devices:
        - "/dev/net/tun"
     env:
        OVPN_FILE: "{{ovpn_file}}"
        PKCS12_FILE: "{{pkcs12_file}}"
        PASS_FILE: "{{pass_file}}"
        OVPN_USERNAME: "{{username}}"
        OVPN_PASSWORD: "{{password}}"
     capabilities:
        - NET_ADMIN
     sysctls: net.ipv6.conf.all.disable_ipv6=0
     volumes:
        - /root/openvpn_docker/{{ ansible_ssh_host }}/:/client/
     detach: true
...
