---
# galaxy_info:
# author: Akash N
# description: "Running openvpn on docker container"
# company: mydbops

# min_ansible_version: 2.9

# platforms:
#   - name: all(linux_systems)
# versions:
#   - all
...
